# Generated by Django 5.0.6 on 2024-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_checkoutpage_contact_faq_helpcenter_homepagecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage_images/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
