# Generated by Django 5.0.6 on 2024-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_rename_homepagecontent_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
